### ISSUE TITLE
How to use AnimePahe url

### ISSUE THREAD

**Issue by athulrajts** [justfoolingaround/animdl#159]
**The inquiry**
how to use the stream urls spat out by grab command from animepahe provider 

```
            "quality": "360",
            "headers": {
                "referer": "https://kwik.cx/e/hLWJn2mQy7tu"
            },
            "stream_url": "https://eu-d1.files.nextcdn.org/stream/0002/69743cc42f53f358e4784909e7c8f67d0a8f25d80d386f6bca12907988d0b6ce/uwu.m3u8"
```
going to stream_url directly gives me 403 forbidden.
i'm guessing i have to do something with the referer. i don't now what.

**Comment by athulrajts** [comment]
i configured vlc

```
default_provider: animixplay
default_player: vlc
players:
  vlc:
    executable: "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe"
    opts: [] 
```
when i do the stream command, it opens vlc, but does not play for anime pahe. but works for other sources.
