### ISSUE TITLE
Using VLC to stream

### ISSUE THREAD

**Issue by Klimred** [justfoolingaround/animdl#209]
I want to use vlc instead of mpv, but this is what i get when running:
`C:\Users\fedor\AppData\Roaming\Python\Python311\site-packages\animdl\core\cli\helpers\player.py:38: UserWarning: Could not find 'vlc' in the system. Falling back to the first available player 'mpv'.`
and this is what i have written in the configs:

```
default_player: "vlc"
players:
  vlc:
    executable: "vlc"
    opts: 
      - --network-caching=5000
      - --play-and-exit
      - --fullscreen
```

**VLC is installed on my PC**

Is there a way to specify the path of the exe yourself or is something different the problem?

**Comment by h4rldev** [comment]
Do you have VLC in path?

**Comment by Klimred** [comment]
I don't think so, it's just installed normally under `C:\Program Files\VideoLAN`
Where should i put it instead?

**Comment by justfoolingaround** [comment]
You can use `C:/Program Files/VideoLAN/vlc.exe` in the `executable` field for `vlc`.

**Comment by Klimred** [comment]
```
preferred_quality: 1080
default_player: vlc
players:
  vlc:
    executable: C:\Program Files\VideoLAN\VLC\vlc.exe
    opts: 
      - --network-caching=5000
      - --play-and-exit
      - --fullscreen
```
I have now changed my configs to this and it works, thank you very much.
