### ISSUE TITLE
Custom configuration in Config directory itself - animdl_config.yml

### ISSUE THREAD

**Issue by Anu-bhav** [justfoolingaround/animdl#80]
Hi @justfoolingaround 

I had an issue with the way animdl loads the custom config `animdl_config.yml`. 

At the moment, it loads from either from `os.getenv('ANIMDL_CONFIG')` or from the `current directory` that we execute animdl `./animdl_config.yml`. 

I did not want to hassle setting ENV variable in windows. 
And as you can see the flaw that if we execute animdl from any other directory, the custom configs do not take effect. 

I misunderstood the docs at first and did not know why my config did not take effect as I created them in both the root folder and in the config folder as well.
I added pprint to know if my config is merged or not.
![image](https://user-images.githubusercontent.com/41940586/143506344-94a0c35a-8826-409c-a945-291a43d53636.png)

Then I went to examine the code and found the issue.

My proposed solution is to search for the `animdl_config.yml` in the config directory itself first.
![image](https://user-images.githubusercontent.com/41940586/143506576-89d73338-a9df-485c-8ec2-92d688610233.png)

I can now run animdl from anywhere and you can now see, it did merge the config.
The code that does the magic:

```CONFIGURATION_FILE_PATH = Path(os.getenv("ANIMDL_CONFIG") or os.path.dirname(os.path.realpath(__file__)) + "/animdl_config.yml" or "./animdl_config.yml")```

My custom config:
```
default_provider: "animixplay"
preferred_quality: 720
default_player: "vlc"
players:
  vlc:
    executable: "vlc"
    opts: 
      - --network-caching=5000
      - --play-and-exit
      - --fullscreen
```

If you want I can make a pull request for you to accept the solution. I will exclude my configuration. 
However for VLC users, it is quite a good configuration as it starts in fullscreen. 
When finished, it autoexits and then the next video starts automatically.
You can provide my config in the docs as a sample for VLC users.
